#!/bin/bash
# SPDX-Identifier: gpl-2.0-or-later
# Copyright (C) 2021, Red Hat, Inc.
#
# Used to do a dummy check
#
# Licensed under the terms of the GNU General Public License as published
# by the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.  You may obtain a copy of the
# license at
#
#    https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

[ -f "${HOME}/.pwmon-rc" ] && source "${HOME}/.pwmon-rc"
[ -f "${HOME}/.cimon-rc" ] && source "${HOME}/.cimon-rc"

source $(dirname $0)/series_db_lib.sh

if [ "$1" != "" ]; then
    pw_instance="$1"
    shift
fi

date=$(date)
echo "Starting dummy at $date" > dummy.log

for branch in $(series_get_active_branches "$pw_instance"); do
    series_id=$(echo $branch | cut -d\| -f1)
    project=$(echo $branch | cut -d\| -f2)
    series_url=$(echo $branch | cut -d\| -f3)
    travis_repo=$(echo $branch | cut -d\| -f4)
    branchname=$(echo $branch | cut -d\| -f5)

    echo "Caught [$series_id]|[$series_url]" >> dummy.log
    
done
