#!/bin/bash
# SPDX-Identifier: gpl-2.0-or-later
# Copyright (C) 2019, Red Hat, Inc.
#
# Licensed under the terms of the GNU General Public License as published
# by the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.  You may obtain a copy of the
# license at
#
#    https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

source $(dirname $0)/series_db_lib.sh

if [ "$1" != "" ]; then
    pw_instance="$1"
    shift
fi

if [ "$1" != "" ]; then
    series_id="$1"
    shift
fi

if [ "$1" != "" ]; then
    series_repo="$1"
    shift
fi

if [ "$1" == "--clear" -o "$1" == "-c" ]; then
    series_branch=""
    shift
elif [ "$1" != "" ]; then
    series_branch="$1"
    shift
fi

if [ "X$pw_instance" == "X" -o "X$series_id" == "X" ]; then
   echo "ERROR: Patchwork instance and series ID are unset."
   echo "Please invoke as: $0 pw_instance series_id series_repo series_branch"
   exit 1
fi

echo "ID:     $series_id"
if ! series_id_exists "$pw_instance" "$series_id"; then
    echo "ERROR: not found on instance $pw_instance"
    exit 1
fi    

if [ "X$series_branch" != "X" ]; then
    series_activate_branch "$pw_instance" "$series_id" "$series_branch" "$series_repo"
else
    series_clear_branch "$pw_instance" "$series_id"
fi
return 0
